export const routeNames = {
  rootPage: 'rootPage',
  home: 'home',
  lifecycleHooks: 'lifecycleHooks',
  nextDomUpdateFlush: 'nextDomUpdateFlush',
  dynamicCss: 'dynamicCss',
  refFamily: 'refFamily',
  preventEventPropagation: 'preventEventPropagation',
  losingReactivity: 'losingReactivity',
  propValidation: 'propValidation',
  writibleComputed: 'writibleComputed',
  watchFamily: 'watchFamily',
  shallowRef: 'shallowRef',
  di: 'di',
  myDirective: 'myDirective',
  customComposableUseToogle: 'customComposableUseToogle',
  customComposableUseCounter: 'customComposableUseCounter',
  untilFunc: 'untilFunc',
  useLocalStorage: 'useLocalStorage',
  customVFocusDeritive: 'customVFocusDeritive'
}
